services:
  - type: web
    name: portfolio-analyzer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --port $PORT --host 0.0.0.0
    pythonVersion: 3.11.9